/*EXCLUINDO BANCO */
DROP DATABASE IF EXISTS CADASTRO;

/*CRIANDO BASE DE DADOS*/
CREATE DATABASE CADASTRO;

/*LISTAR BASES*/
SHOW DATABASES;

/*USANDO UM BANCO*/
USE CADASTRO;

/*CRIANDO TABELAS*/
 CREATE TABLE ALUNO(
    ID int(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOME varchar(50) NOT NULL,
    SOBRE_NOME varchar(50) NOT NULL,
    CPF bigint(15) NOT NULL
) ENGINE = INNODB;

/*TABELA TURMA*/
CREATE TABLE TURMA (
	ID_TURMA int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PROFESSOR int(11) NULL,
    NOME_TURMA varchar(255) NULL   
) ENGINE = INNODB;

/*adicionando nova coluna*/
ALTER TABLE aluno ADD id_turma int(11);

/*adicionando como foreing key*/
ALTER TABLE aluno
ADD CONSTRAINT FK_TURMA
FOREIGN KEY (id_turma)
REFERENCES turma (ID_TURMA);

/*MOSTRAR TABLEAS*/
SHOW TABLES;

/*MOSTRAR ESTUTURA DE UMA TABELA*/
DESCRIBE TURMA



