USE VIRTUALDC;

-- CASO PRECISE ATUALIZAR UMA PROCEDURE APAGAR E DEVE CRIAR DE NOVO OU USAR O COMANDO ALTER PROCEDURE
DROP PROCEDURE SP_ADMINITE;

GO

CREATE PROCEDURE SP_ADMINITE @CODIGO INT
AS

	BEGIN

	-- ESTAMOS POPULANDO UMA TABELA COM DADOS DE OUTRA TABELA
	INSERT INTO morto
	SELECT CODFUN, NOME, DEPTO, FUNCAO, SALARIO, ADMISSAO, FILHOS FROM CADFUN
	WHERE CODFUN = @CODIGO;

	-- DELETAR O CODIGO DA TABELA PRINCIPAL
	DELETE FROM CADFUN WHERE CODFUN = @CODIGO;

	END
GO


--SELECT * FROM CADFUN;
EXEC SP_ADMINITE 9
--SELECT * FROM morto;
