USE VIRTUALDC;

-- VERIFICANDO ONDE OS CAMPOS SAO NULL OU SEJA NAO FOI PREENCHIDO
SELECT CODFUN, NOME, FILHOS FROM CADFUN WHERE FILHOS IS NULL;

-- VERIFICANDO COM O OPERADOR DE NEGACAO
SELECT CODFUN, NOME, FILHOS FROM CADFUN WHERE NOT FILHOS IS NULL;

-- VERIFICANDO COM OPERADOR DE NEGACAO
SELECT CODFUN, NOME, ADMISSAO FROM CADFUN WHERE NOT ADMISSAO IS NULL;