USE VIRTUALDC;

-- USANDO O OPERADR LIKE ELE SERVE PARA ENCONTRAR VALORES DENTRO DOS REGISTROS

-- VALORES QUE COMECEM COM ONZE
SELECT NOME,DEPTO, SALARIO FROM CADFUN WHERE SALARIO LIKE '11%';

-- VALORES QUE TENHAM OITO EM QUALQUER LUGAR
SELECT NOME, DEPTO, SALARIO FROM CADFUN WHERE SALARIO LIKE '%8%';

-- VALORES QUE TENHAM ZERO NA SEGUNDA POSICAO
SELECT NOME, DEPTO, SALARIO FROM CADFUN WHERE SALARIO LIKE '_0';

-- VALORES QUE TENHAM UM E TENHAM 3 CARACTERES DE COMPRIMENTO
SELECT NOME, DEPTO, SALARIO FROM CADFUN WHERE SALARIO LIKE '1_%_%';

-- VALORES QUE TERMINEM COM O NUMERO 6
SELECT NOME, DEPTO, SALARIO FROM CADFUN WHERE SALARIO LIKE '6%';

-- VALORES QUE TENHAM UM NA SEGUNDA POSICAO E TERMINEM COM O NUMERO 6
SELECT NOME, DEPTO, SALARIO FROM CADFUN WHERE SALARIO LIKE '_1%6';
