USE VIRTUALDC;

-- USANDO O OPERADOR DE INTERVALO BETWEEN
SELECT NOME, FILHOS, SALARIO FROM CADFUN WHERE SALARIO BETWEEN 1700 AND 2000;

-- USANDO O OPERADOR DE NEGACAO JUNTO COM O BETWEEN
SELECT NOME, FILHOS, SALARIO FROM CADFUN WHERE NOT SALARIO BETWEEN 1700 AND 2000;

