USE VIRTUALDC;


UPDATE CADFUN SET FILHOS = 1 WHERE CODFUN = 2;
UPDATE CADFUN SET FILHOS = 3 WHERE CODFUN = 3;
UPDATE CADFUN SET FILHOS = 2 WHERE CODFUN = 5;
UPDATE CADFUN SET FILHOS = 1 WHERE CODFUN = 9;
UPDATE CADFUN SET FILHOS = 4 WHERE CODFUN = 10;
UPDATE CADFUN SET FILHOS = 3 WHERE CODFUN = 11;

SELECT * FROM CADFUN WHERE FILHOS IS NOT NULL;
