USE VIRTUALDC;

-- ALTERANDO A TABELA PARA ADICIONAR AUTO INCREMENTO 
-- ISSO IRA FAZER PERDER OS DADOS DA COLUNA

-- 1 . REMOVER RESTRINCAO DE PRIMARY KEY PARA CONSEGUIR APAGAR A COLUNA 
ALTER TABLE cadfun DROP CONSTRAINT PK__cadfun__CC5E8D38ABB41F75;

-- 2. REMOVER A COLUNA ANTIGA
ALTER TABLE cadfun DROP COLUMN CODFUN;

-- 3. ADICIONAR A NOVA COLUNA QUE TEM ESSA RESTRINCAO DE AUTO INCREMENTO
ALTER TABLE cadfun ADD CONDFUN INT IDENTITY(1,1) PRIMARY KEY;

