-- SELECIONANDO O BANDO DE DADOS
USE VIRTUALDC;

-- CRIANDO UMA TABELA PARA O BANCO DE DADOS
CREATE TABLE cadfun (
	-- CHAVE PRIMARIA
	CODFUN INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(40) NOT NULL,
	DEPT CHAR(2),
	FUNCAO CHAR(20),
	SALARIO DECIMAL(10,2)
);
