-- FUNCAO COUNT ELA CONTA O NUMERO DE LINHAS DIANTE DE CRITERIO
USE VIRTUALDC;

-- CONTE O NUMERO DE LINHAS DENTRO DESSE CRITERIO
SELECT COUNT(*) FROM CADFUN WHERE DEPTO = 3;

-- CONTE SO AS LINHAS ONDE A FUNCAO É UM SUPERVISOR E TENHA FILHOS
SELECT COUNT(*) FROM CADFUN WHERE FUNCAO = 'SUPERVISOR' AND FILHOS > 3;
