USE VIRTUALDC;

-- TRABALHANDO COM DATAS ASSUNTO DATEFIFF
/* DATEDIFF É UMA FUNÇÃO QUE VERIFICA A DIFENÇA ENTRE DUAS DATAS
*/

SELECT -- COMANDO DE SELEÇÃO
NOME,-- CAMPO NOME
DATEDIFF( -- FUNÇÃO QUE VERIFICA A DIFERENÇA ENTRE DATAS
DAY, -- A DIFERENCA SERA CONTABILIZADA EM DIAS
ADMISSAO, -- UMA DATA PARA COMPARACAO NESSE CASO A DATA DE ADMISSAO
'15/09/2017' -- OUTRA DATA PARA COMPARAÇÃO NESSE CASO UMA STRING 
) 
FROM
CADFUN; -- TABELA SELECIONADA

-- PERCEBA QUE ESTAMOS COMPARANDO A DISTANCIA ENTRE AOS QUANTOS ANOS DE DIFERENÇA ?
SELECT 
NOME,
DATEDIFF(YEAR, ADMISSAO, '01/01/2026') FROM CADFUN;

-- AGORA PARA MES
SELECT
NOME,
DATEDIFF(MONTH, ADMISSAO, '01/01/2026') FROM CADFUN;

-- AGORA EM SEMANA
SELECT
NOME,
DATEDIFF(WEEKDAY,ADMISSAO, '01/01/2026') FROM CADFUN;

/* EM RESUMO A DATEDIFF() RECEBE COMO ARGUMENTO DA FUNÇÃO TRES DADOS
1º QUAL O TIPO DE COMPARAÇÃO
ANO = YEAR
MES = MONTH
SEMANA = WEEKDAY
DIAS = DAY
HORAS = HOUR
E ASSIM SUCESSIVAMENTE
*/