USE VIRTUALDC;
-- FUNCOES DE BANCO DE DADOS

-- FUNCAO PARA CALCULAR A MEDIA
SELECT AVG(SALARIO) FROM CADFUN;

-- FUNCAO PARA CALULAR A MEDIA SEM PERMITIR SALARIO DUPLICADO
SELECT AVG(DISTINCT SALARIO) FROM CADFUN;

-- FUNCAO PARA CALCULAR COM WHERE 
SELECT AVG(SALARIO) FROM CADFUN WHERE DEPTO = '3';

-- FUNCAO PARA CALCULAR COM CONDICAO SEM REPETICAO
SELECT AVG(DISTINCT SALARIO) FROM CADFUN WHERE DEPTO = '3';