USE VIRTUALDC;

-- FUNCOES PARA OPERAR SOBRE DATAS
/*
DATEADD()  =  ADICIONAR UM NUMERO DE DIAS A UMA DATA EPECIFICA
DATEDIFF() =  REPRESENTA A DIFERENCA ENTRE DIAS ENTRE AS DATAS FORNECIDAS
DATENAME() = RETORNA O NOME DO MES DE UMA DATA
DATEPART() = RETORNA O VALOR DE UMA PARTE DE UMA DATA (ANO,TRIMESTRE, HORA ...)
GETDATE()  = RETORNA RETORNA O VALOR DA DATA ATUAL DO SISTEMA
MONTH()    = RETORNA O MES ATUAL DE UMA DATA INFORMADA
DAY()      = RETORNA O DIA DE UMA DATA INFORMADA
YEAR()     = RETORNA O ANO DE UMA DATA INFORMADA


PARA OS ARGUMENTOS DAS FUNCOES PODEMOS ULTILIZAR:

YEAR = ANO
QUARTER = TRIMESTRE
MONTH = MES
DAYOFYEAR = DETERMINA O DIA DO ANO
DAY = O DIA
WEEK = A SEMANA
WEEKDAY = O DIA DA SEMANA
HOUR = HORA
MINUTE = MINUTO
SECOND = SEGUNDO
MILLISECOND = MILISEGUNDO
MICROSECOND = MICRO SEGUNDOS
NANOSECOND = NANO SEGUNDOS
*/

-- FUNÇÃO DATEADD()
-- ADICIONE UM NUMERO INTEIRO A UMA PARTE DA DATA PARA ADICIO-LO A MESMA

-- ADICIONAR UM MES A UMA DATA
SELECT DATEADD(MONTH, 1, '26/03/1965');

-- ADICIONAR UM DIA A UMA DATA
SELECT DATEADD(DAY, 1, '26/03/1965');

-- ADICIONAR UM ANO A UMA DATA
SELECT DATEADD(YEAR, 1, '26/03/2026');

-- DATADIFF()
-- RETORNA UM VALOR INTEIRO DA DIFERENCE ENTRE DUAS DATAS

-- RETORNA A DIFERENCA EM DIAS ENTRE A DATA DE ADMISSAO E UMA DATA INFORMADA
SELECT NOME, DATEDIFF(YEAR, ADMISSAO, '15/09/2017') FROM CADFUN;

-- DATANAME()
-- UMA CADEIA DE CARACTERES QUE REPRESENTA UMA PARTE DE UMA DATA ESPECIFICA


SELECT NOME, ADMISSAO, DATENAME(MONTH, ADMISSAO) FROM CADFUN; -- ESCREVENDO O MES DE CADASTRO
SELECT NOME, ADMISSAO, DATENAME(DAY, ADMISSAO) FROM CADFUN; -- MOSTRANDO O DIA DE ADMISSAO

-- GETDATE()
-- PEGA A DATA ATUAL DO SERVIDOR
SELECT GETDATE();

-- DATEPART()
-- RETORNA UM VALOR INTEIRO QUE REPRESENTA UMA PARE DE UMA DATA INFORMADA

SELECT DATEPART(DAY,GETDATE());     -- PEGANDO O DIA ATUAL
SELECT DATEPART(MINUTE,GETDATE());  -- PEGANDO O MINUTO ATUAL
SELECT DATEPART(WEEKDAY,GETDATE()); -- VERIFICAR QUE DIA DA SEMANA É HOJE
