-- USANDO O BANCO DE DADOS
USE dbteste;
-- INSERINDO AS CATEGORIAS
INSERT INTO categoria VALUES (1,'Eletrodomesticos');
INSERT  INTO  categoria VALUES  (2,'CAMA, MESA BANHO');
INSERT INTO  categoria VALUES  (3,'AUDIO E VIDEO');
INSERT INTO  categoria VALUES  (4,'INFORMÁTICA');
INSERT  INTO  categoria VALUES (5, 'ARTIGOS ESPORTIVOS');
-- INSERINDO AS SUBSCATEGORIAS
INSERT INTO sub_categoria VALUES (1, 'BOLAS DE FUTEBOL',5);
INSERT INTO sub_categoria VALUES (2, 'CAMISETA DE FUTEBOL',5);
INSERT INTO sub_categoria VALUES (3, 'TÊNIS E CHUTEIRAS',5);
INSERT INTO sub_categoria VALUES (4, 'RAQUETES DE TENIS',5);
INSERT INTO sub_categoria VALUES (5, 'DVD',3);
INSERT INTO sub_categoria VALUES (6, 'CDS',3);
INSERT INTO sub_categoria VALUES (7, 'APARELHO DE SOM' , 3);