USE VIRTUALDC;

-- APAGA UMA TABELA CASO ELA EXISTA
DROP TABLE IF EXISTS CLIENTE;

-- CRIA UMA TABELA
CREATE TABLE CLIENTE (
	
	CODCLI CHAR(3) NOT NULL PRIMARY KEY,
	NOME CHAR(40) NOT NULL,
	ENDERECO CHAR(50) NOT NULL,
	CIDADE VARCHAR(40) NOT NULL,
	ESTADO CHAR(5) NOT NULL,
	CEP CHAR(40)
);

-- INSERE DADOS EM UMA TABELA
INSERT INTO CLIENTE VALUES (
'250',
'BANCO BARCA S/A',
'R. VITO, 34',
'SAO SEBASTIAL',
'CE',
'62380-000'
);

-- SELECIONAR OS DADOS DA TABELA
SELECT NOME, CIDADE, ESTADO FROM CLIENTE;

-- INSERINDO DADOS EM LOTE

-- INSERIR OS DADOS CONSTANTES NA PAGINA 146
INSERT INTO CLIENTE VALUES ()
