USE VIRTUALDC;

-- VER TODAS AS TABELAS DO BANCO DE DADOS SELECIONADO
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE';

--PARA VER DETALHES DE UMA TABEL NO SQL SERVER PODEMOS USAR O SEGUINTE COMANDO
EXEC SP_HELP CADFUN;
