USE VIRTUALDC;

SELECT * FROM CADFUN;

-- LISTAR OS CARGOS EXISTENTES EM DESCRECENTE DAS QUANTIDADADES DE FUNCIONARIOS ATIVOS
SELECT FUNCAO, COUNT(*) FROM CADFUN GROUP BY FUNCAO ORDER BY COUNT(*) DESC; -- LEMBRANDO QUE NESSA TABELA FICAM APENAS OS CARGOS ATIVOS

-- LISTAR TODOS OS FUNCIONARIO DO DEPARTAMENTO 5 ESTANDO ATIVOS OU DESATIVADOS
SELECT * FROM CADFUN WHERE DEPTO = 5
UNION
SELECT * FROM morto WHERE DEPTO = 5;

-- SELECIONAR FUNCIONARIO QUE TEM 1,2,3,4 FILHOS E MOSTRAR EM DECRESSENTE O NUMERO DE FILHOS
SELECT * FROM CADFUN WHERE FILHOS IN(1,2,4,3)
UNION
SELECT * FROM morto WHERE FILHOS IN(1,2,3,4)

ORDER BY 7 DESC;
-- ESTOU DIZENDO QUAL COLUNA FAZER A ORDENAÇÃO, PODERIA SER O NOME DA COLUNA POREM ELA TERIA QUE 
-- TER O MESMO NOME NAS TABELAS OU USAR ALIAS PARA OS NOMES DOS CAMPOS;

-- LISTAR A QUANTIDADE DE FUNCIONARIOS QUE TENHAM O SOBRENOME SILVA
SELECT COUNT(*) FROM CADFUN WHERE NOME LIKE '%SILVA%';

