USE VIRTUALDC;

-- USANDO UNION 
SELECT CODFUN, NOME FROM CADFUN UNION
SELECT CODFUN, NOME FROM morto

/*
1. AO CRIAR UMA UNION ESTAMOS NO FINAL CRIANDO UMA UNICA TABELA OU SEJA 
O RESULTADO DA UNIAO SERA UMA TABELA UNICA POR ISSO PRECISAMOS QUE 
AS DUAS TENHAM O MESMO NUMERO DE CAMPOS E SEQUENCIA E TIPO ISSO PORQUE FICARÃO UMA
A BAIXO DA OUTRA, DESSA FORMA POR EXEMPLO NAO FAZ SENTIDO NA COLUNA DE 
NOMES FICAR A DATA DE NASCIMENTO

2. CASO HAJA OUTRO REGISTRO COM MESMO IDENTIFICADOR A UNIAO VAI MOSTRAR APENAS UM
É COMO SE ELA AGRUPASSE PELO CODIGO, CASO EXISTA MAIS DE UM E SEJA NESCESSARIO MOSTRAR TODOS
DEVEMOS ULTILIZAR O COMANDO ALL

*/
-- TOPICO 1
SELECT CODFUN, NOME FROM CADFUN UNION
SELECT CODFUN, FUNCAO FROM morto -- A FUNCAO VAI MOSTRAR ABAIXO DE NOME NAS FAZ SENTIDO

-- TOPICO 2
SELECT CODFUN, NOME FROM CADFUN UNION ALL -- ESSE COMANDO ALL INDICA QUE QUEREMOS MOSTRAR TODOS OS DADOS MESMO QUE HAJA OUTRO CODIGO IGUAL
SELECT CODFUN, FUNCAO FROM morto;

